package interfaces;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */





import conexion.conexion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class InicioDeSesion extends javax.swing.JFrame {
    
    public static Registro re; 
    
    conexion con= new conexion();
    Connection cn =con.conectar();
    
    public InicioDeSesion() {
                
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bntIniciar = new javax.swing.JButton();
        bntRegistro = new javax.swing.JButton();
        bntOlvideContraseña = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Inicio de sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 16));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 39, -1));

        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 312, 22));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        bntIniciar.setBackground(new java.awt.Color(102, 153, 255));
        bntIniciar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bntIniciar.setForeground(new java.awt.Color(255, 255, 255));
        bntIniciar.setText("Ingresar");
        bntIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(bntIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        bntRegistro.setBackground(new java.awt.Color(102, 153, 255));
        bntRegistro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bntRegistro.setForeground(new java.awt.Color(255, 255, 255));
        bntRegistro.setText("Registrate");
        bntRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(bntRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        bntOlvideContraseña.setBackground(new java.awt.Color(102, 153, 255));
        bntOlvideContraseña.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bntOlvideContraseña.setForeground(new java.awt.Color(255, 255, 255));
        bntOlvideContraseña.setText("Olvide mi contraseña");
        bntOlvideContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOlvideContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(bntOlvideContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, 24));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("¿Aún no tenes cuenta?   ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, 24));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Accede a mejores beneficios, registrandote.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 312, 22));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 350, 490));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Logo.jpeg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Nubes.jpeg")); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 840, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistroActionPerformed
        dispose();
        new Registro().setVisible(true);
    }//GEN-LAST:event_bntRegistroActionPerformed

    private void bntIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIniciarActionPerformed
          String correo= txtCorreo.getText();
        String contraseña=txtContraseña.getText();
        if(!correo.equals("")||!contraseña.equals("")){
            try{
                PreparedStatement ps=cn.prepareStatement("SELECT * FROM usuarios WHERE correo = ? AND contraseña = ?");
                ps.setString(1, correo);
                ps.setString(2, contraseña);            
                ResultSet rs=ps.executeQuery();
                if(rs.next()){
                    dispose();
                    primeraParteBoletos primeraparte= new primeraParteBoletos();
                    primeraparte.setVisible(true);
                }else{
                  JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos");  
                }
                rs.close();
                ps.close();
                cn.close();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error al iniciar sesión");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debe completar los datos");
        }
    }//GEN-LAST:event_bntIniciarActionPerformed

    private void bntOlvideContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOlvideContraseñaActionPerformed
       dispose();
       new RecuperacionDeContraseña().setVisible(true);
    }//GEN-LAST:event_bntOlvideContraseñaActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntIniciar;
    private javax.swing.JButton bntOlvideContraseña;
    private javax.swing.JButton bntRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
