/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author SFTA
 */
public class MetodosDePago extends javax.swing.JFrame {

   
    public MetodosDePago() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkTarjetaDeCredito = new javax.swing.JCheckBox();
        checkTarjetaDeDebito = new javax.swing.JCheckBox();
        checkMercadoPago = new javax.swing.JCheckBox();
        chekRapipago = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        chekPagoFacil = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Métodos de Pago");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 127, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Seleccione un método de pago:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 170, -1, -1));

        checkTarjetaDeCredito.setBackground(new java.awt.Color(255, 255, 255));
        checkTarjetaDeCredito.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        checkTarjetaDeCredito.setForeground(new java.awt.Color(0, 51, 102));
        checkTarjetaDeCredito.setText("Tarjeta de Crédito");
        checkTarjetaDeCredito.setBorder(null);
        checkTarjetaDeCredito.setBorderPainted(true);
        checkTarjetaDeCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTarjetaDeCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(checkTarjetaDeCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 215, -1, -1));

        checkTarjetaDeDebito.setBackground(new java.awt.Color(255, 255, 255));
        checkTarjetaDeDebito.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        checkTarjetaDeDebito.setForeground(new java.awt.Color(0, 51, 102));
        checkTarjetaDeDebito.setText("Tarjeta de Débito");
        jPanel1.add(checkTarjetaDeDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 253, -1, -1));

        checkMercadoPago.setBackground(new java.awt.Color(255, 255, 255));
        checkMercadoPago.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        checkMercadoPago.setForeground(new java.awt.Color(0, 51, 102));
        checkMercadoPago.setText("Mercado Pago");
        checkMercadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMercadoPagoActionPerformed(evt);
            }
        });
        jPanel1.add(checkMercadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 295, -1, 21));

        chekRapipago.setBackground(new java.awt.Color(255, 255, 255));
        chekRapipago.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        chekRapipago.setForeground(new java.awt.Color(0, 51, 102));
        chekRapipago.setText("Rapipago");
        jPanel1.add(chekRapipago, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 334, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Proceder a pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 414, -1, -1));

        chekPagoFacil.setBackground(new java.awt.Color(255, 255, 255));
        chekPagoFacil.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        chekPagoFacil.setForeground(new java.awt.Color(0, 51, 102));
        chekPagoFacil.setText("Pago Fácil");
        jPanel1.add(chekPagoFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 376, -1, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 320, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Logo.jpeg")); // NOI18N
        jLabel5.setAutoscrolls(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Nubes.jpeg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 830, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkTarjetaDeCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTarjetaDeCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTarjetaDeCreditoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     manejarSeleccionDePago();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkMercadoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMercadoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMercadoPagoActionPerformed


private void manejarSeleccionDePago() {
    int seleccionados = 0;

    if (checkTarjetaDeCredito.isSelected()) seleccionados++;
    if (checkTarjetaDeDebito.isSelected()) seleccionados++;
    if (checkMercadoPago.isSelected()) seleccionados++;
    if (chekRapipago.isSelected()) seleccionados++;
    if (chekPagoFacil.isSelected()) seleccionados++;

    if (seleccionados > 1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione solo un método de pago.");
        return;
    }

    if (checkTarjetaDeCredito.isSelected()) {
        abrirFormularioTarjetaCredito();
    } else if (checkTarjetaDeDebito.isSelected()) {
        abrirFormularioTarjetaDebito();
    } else if (checkMercadoPago.isSelected()) {
        abrirFormularioMercadoPago();
    } else if (chekRapipago.isSelected()) {
        abrirFormularioRapipago();
    } else if (chekPagoFacil.isSelected()) {
        abrirFormularioPagoFacil();
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un método de pago.");
    }
}

private void abrirFormularioTarjetaCredito() {
    dispose();
    new Tarjetas().setVisible(true);
}

private void abrirFormularioTarjetaDebito() {
    dispose();
    new Tarjetas().setVisible(true);
}

private void abrirFormularioMercadoPago() {
    dispose();
    new MercadoPago().setVisible(true);
}

private void abrirFormularioRapipago() {
    dispose();
    new MercadoPago().setVisible(true);
}

private void abrirFormularioPagoFacil() {
    dispose();
    new MercadoPago().setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkMercadoPago;
    private javax.swing.JCheckBox checkTarjetaDeCredito;
    private javax.swing.JCheckBox checkTarjetaDeDebito;
    private javax.swing.JCheckBox chekPagoFacil;
    private javax.swing.JCheckBox chekRapipago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
