/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SFTA
 */
public class Tarjetas extends javax.swing.JFrame {

conexion cone =new conexion();
    Connection cn=cone.conectar();
    public Tarjetas() {
        initComponents();
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumeroTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtvencimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigoCVV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnombreTitular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtapellidoTitular = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Datos de la tarjeta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Número de Tarjeta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        txtnumeroTarjeta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnumeroTarjeta.setText("0000 0000 0000 0000");
        txtnumeroTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        txtnumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 313, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, -1, -1));

        txtvencimiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtvencimiento.setText("MM/AA");
        txtvencimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        txtvencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvencimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtvencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 128, 23));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Vencimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Código CVV");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        txtcodigoCVV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcodigoCVV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        txtcodigoCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoCVVActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodigoCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 128, 23));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Nombre del titular de la tarjeta");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        txtnombreTitular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnombreTitular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        txtnombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreTitularActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombreTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 313, 25));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Apellido del titular de la tarjeta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        txtapellidoTitular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtapellidoTitular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel1.add(txtapellidoTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 313, 25));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("DNI");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        txtdni.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 313, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 313, 25));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 380, 520));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Logo.jpeg")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Nubes.jpeg")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvencimientoActionPerformed

    private void txtcodigoCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoCVVActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniActionPerformed

    private void txtnombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreTitularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String numeroTarjeta = txtnumeroTarjeta.getText().trim();
    String vencimiento = txtvencimiento.getText().trim();
    String codigoCVV = txtcodigoCVV.getText().trim();
    String nombreTitular = txtnombreTitular.getText().trim();
    String apellidoTitular = txtapellidoTitular.getText().trim();
    String dni = txtdni.getText().trim();
    String correo = txtcorreo.getText().trim();
    
    // Validar campos vacíos
    if (numeroTarjeta.isEmpty() || vencimiento.isEmpty() || codigoCVV.isEmpty() || nombreTitular.isEmpty() || apellidoTitular.isEmpty() || dni.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }
    
    // Validar el formato del número de tarjeta
    if (!numeroTarjeta.matches("\\d{4} \\d{4} \\d{4} \\d{4}")) {
        JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener el formato 0000 0000 0000 0000.");
        return;
    }

    // Validar el formato del CVV
    if (!codigoCVV.matches("\\d{3}")) {
        JOptionPane.showMessageDialog(this, "El código CVV debe tener 3 dígitos.");
        return;
    }

    // Validación del vencimiento (formato MM/AA)
    if (!vencimiento.matches("\\d{2}/\\d{2}")) {
        JOptionPane.showMessageDialog(this, "El vencimiento debe tener el formato MM/AA.");
        return;
    }
    
    // Validación de vencimiento de tarjeta
    try {
        String[] parts = vencimiento.split("/");
        int mes = Integer.parseInt(parts[0]);
        int anio = Integer.parseInt(parts[1]);
        if (mes < 1 || mes > 12) {
            JOptionPane.showMessageDialog(this, "El mes de vencimiento debe estar entre 01 y 12.");
            return;
        }

        // Fecha actual
        java.util.Calendar now = java.util.Calendar.getInstance();
        int currentYear = now.get(java.util.Calendar.YEAR) % 100;
        int currentMonth = now.get(java.util.Calendar.MONTH) + 1; // Mes es 0-indexado

        // Verificación
        if (anio < currentYear || (anio == currentYear && mes < currentMonth)) {
            JOptionPane.showMessageDialog(this, "La tarjeta ha expirado.");
            return;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El vencimiento debe tener el formato MM/AA.");
        return;
    }

    guardarDatosTarjeta(numeroTarjeta, vencimiento, codigoCVV, nombreTitular, apellidoTitular, dni, correo);
    dispose();
    new ConfirmacionDeCompra().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroTarjetaActionPerformed
private void guardarDatosTarjeta(String numeroTarjeta, String vencimiento, String codigoCVV, String nombreTitular, String apellidoTitular, String dni, String correo) {
        

        String sql = "INSERT INTO tarjetas (numero_tarjeta, vencimiento, codigo_cvv, nombre_titular, apellido_titular, dni, correo ) VALUES ( ?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement preparedStatement = cn.prepareStatement(sql);
            preparedStatement.setString(1, numeroTarjeta);
            preparedStatement.setString(2, vencimiento);
            preparedStatement.setString(3, codigoCVV);
            preparedStatement.setString(4, nombreTitular);
            preparedStatement.setString(5, apellidoTitular);
            preparedStatement.setString(6, dni);
            preparedStatement.setString(7, correo);
           

            int filasAfectadas = preparedStatement.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Datos de la tarjeta guardados exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar los datos de la tarjeta.");
            }

            cn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellidoTitular;
    private javax.swing.JTextField txtcodigoCVV;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombreTitular;
    private javax.swing.JTextField txtnumeroTarjeta;
    private javax.swing.JTextField txtvencimiento;
    // End of variables declaration//GEN-END:variables
}
