/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class VuelosComprados extends javax.swing.JFrame {

    conexion cone =new conexion();
    Connection cn=cone.conectar();
    public VuelosComprados() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        btnBuscarVuelos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVuelosComprados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEliminarVuelo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Vuelos Realizados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Ingrese su gmail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        jPanel1.add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 103, 313, -1));

        btnBuscarVuelos.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscarVuelos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBuscarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVuelos.setText("Buscar");
        btnBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVuelosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 100, -1, -1));

        tableVuelosComprados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableVuelosComprados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 147, 677, 237));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 432, -1, -1));

        btnEliminarVuelo.setBackground(new java.awt.Color(102, 153, 255));
        btnEliminarVuelo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEliminarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVuelo.setText("Eliminar Vuelo");
        btnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVueloActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 429, -1, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Logo.jpeg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\OneDrive\\Escritorio\\Imagenes Boleto de Avion\\Nubes.jpeg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 830, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new primeraParteBoletos().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVuelosActionPerformed
      String emailUsuario = txtGmail.getText().trim();

        if (emailUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su Gmail.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "SELECT id_pago, origen, destino, fecha_ida, fecha_vuelta, precio_final, cantidad_pasajeros, medio_pago, hora FROM vuelos_pagados WHERE email_usuario = ?";
        try (PreparedStatement pstmt = cn.prepareStatement(sql)) {
            pstmt.setString(1, emailUsuario);
            ResultSet rs = pstmt.executeQuery();

            DefaultTableModel modelo = new DefaultTableModel(new String[]{
                "ID", "Origen", "Destino", "Fecha Ida", "Fecha Vuelta", "Precio Final", "Cantidad Pasajeros", "Medio Pago", "Hora"
            }, 0);

            while (rs.next()) {
                int id = rs.getInt("id_pago");
                String origen = rs.getString("origen");
                String destino = rs.getString("destino");
                Date fechaIda = rs.getDate("fecha_ida");
                Date fechaVuelta = rs.getDate("fecha_vuelta");
                double precioFinal = rs.getDouble("precio_final");
                int cantidadPasajeros = rs.getInt("cantidad_pasajeros");
                String medioPago = rs.getString("medio_pago");
                Time hora = rs.getTime("hora");

                modelo.addRow(new Object[]{id, origen, destino, fechaIda, fechaVuelta, precioFinal, cantidadPasajeros, medioPago, hora});
            }

            tableVuelosComprados.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarVuelosActionPerformed

    private void btnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVueloActionPerformed
        int selectedRow = tableVuelosComprados.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un vuelo de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idVuelo = (int) tableVuelosComprados.getValueAt(selectedRow, 0);
        Date fechaIda = (Date) tableVuelosComprados.getValueAt(selectedRow, 3);
        Date fechaVuelta = (Date) tableVuelosComprados.getValueAt(selectedRow, 4);
        Date today = new Date();

        if (today.after(fechaIda) || today.after(fechaVuelta)) {
            JOptionPane.showMessageDialog(this, "No puede eliminar un vuelo que ya ha pasado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cancelar este vuelo?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM vuelos_pagados WHERE id_pago = ?";
            try (PreparedStatement pstmt = cn.prepareStatement(sql)) {
                pstmt.setInt(1, idVuelo);
                int affectedRows = pstmt.executeUpdate();
                if (affectedRows > 0) {
                    ((DefaultTableModel) tableVuelosComprados.getModel()).removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Cancelación realizada con éxito. Su reembolso llegará en los próximos 7 días hábiles.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo cancelar el vuelo. Intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al cancelar el vuelo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_btnEliminarVueloActionPerformed

 
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVuelos;
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVuelosComprados;
    private javax.swing.JTextField txtGmail;
    // End of variables declaration//GEN-END:variables
}
